# Generated by Django 4.1 on 2023-11-06 09:53

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_color_person_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="image",
            field=models.ImageField(
                default="posts/default.jpg",
                upload_to=home.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
